#!/usr/bin/sh
#
# Helper script for deploying dotfiles. 
# usage: deploy bash /home/david/.dotfiles/bash/bashrc /home/david/.bashrc
#

if [ $# -ne 3 ]; then 
	printf >&2 "$0: Wrong number of arguments\n"
	exit 1
fi

PACKAGE_NAME="$1"
SOURCE_FILE="$2"
DEST_FILE="$3"
DOTFILES="$(pwd)"

printf "%s\n    %s -> %s\n" "$PACKAGE_NAME" "$SOURCE_FILE" "$DEST_FILE" 

if [ -d "$SOURCE_FILE" ]; then
	cp -nr $DEST_FILE $DOTFILES/backup/ 
	if [ -e $DEST_FILE ]; then
		# When creating symlink to a directory, if that directory 
		# already exists the symlink will be created within the directory
		# rather than replacing it.  Removing the existing directory
		# before creating the symlink is the solution
		
		# Too dangerous to remove existing directory using 
		# rm -rf $DEST_FILE
		
		# Play it safe..
		echo "*** Existing directory $DEST_FILE must be manually removed, before repository version can be deployed ***"
		exit 1
		
	else
		ln -fsn $SOURCE_FILE $DEST_FILE
	fi
	
else
	mkdir -p $DOTFILES/backup/$PACKAGE_NAME && cp -n $DEST_FILE $DOTFILES/backup/$PACKAGE_NAME/
	ln -fs $SOURCE_FILE $DEST_FILE
fi
