HISTSIZE=10000
SAVEHIST=10000

#alias ls='ls -hF --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias ls='ls -hF --group-directories-first --color=auto'
alias ll='ls -l'
alias la='ls -la'
alias lt='ls -lrt'                  # sort by modification time
alias lx='ls -lBX'                  # sort by extension
alias lz='ls -lrS'                  # sort by size

alias grep='grep --color=auto -d skip'
alias cp="cp -i"                    # confirm before overwriting something
alias df='df -h'                    # human readable
alias du='du -hc'                   # human readable
alias free='free -m'                # show sizes in MB
alias pm='sudo pacman'
alias pk='packer --noconfirm --noedit'
alias cpufreq='watch grep \"cpu MHz\" /proc/cpuinfo'

